[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
bevy = "0.7"
bevy_flycam = "0.7"
bevy_eventwork = "0.7"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["fast-compile"]
fast-compile = ["bevy/dynamic"]
